Order: {
  shape: class
  +id: String
  +submit(String coupon): bool
}
Entity <- Order: {source-arrowhead: {shape: triangle; style.filled: false}}
Order <- LineItem: {source-arrowhead: {shape: diamond; style.filled: true}}
Order -> Customer: placed by
