start: "" {shape: circle; width: 20; height: 20}
start -> Active
end: "" {shape: circle; style.double-border: true; width: 24; height: 24}
Active -> end
Active: {
  start: "" {shape: circle; width: 20; height: 20}
  start -> Idle
  Idle -> Running: start
  Running -> Idle: stop
}
